# services:
#   rabbitmq:
#     image: rabbitmq:3.11-management
#     ports:
#         - 5672:5672
#         - 15672:15672
#     environment:
#         - "RABBITMQ_DEFAULT_PASS=admin"
#         - "RABBITMQ_DEFAULT_USER=admin"
#         - "RABBITMQ_DEFAULT_VHOST=vhost"
#     networks:
#       - cms-rabbitmq
#     expose:
#       - 5672
#       - 15672
#   mongo:
#     container_name: mongo
#     image: 'mongo:5'
#     volumes:
#       - ./data:/data/db
#     environment:
#         MONGO_INITDB_DATABASE: 'admin'
#         MONGO_INITDB_ROOT_USERNAME: 'cms-video'
#         MONGO_INITDB_ROOT_PASSWORD: '***********************'
#     restart: on-failure
#     command: mongod --port 27018
#     ports:
#       - '27018:27018'
#     networks:
#       - cms-mongo
#     expose:
#       - 27018
#   cms-video:
#     container_name: cms-video
#     restart: always
#     build: .
#     ports:
#       - '5050:5050'
#     depends_on:
#       - rabbitmq
#       - mongo
#     networks:
#       - cms-mongo
#       - cms-rabbitmq

# networks:
#   cms-mongo:
#   cms-rabbitmq: